# Generated by Django 3.1.3 on 2022-03-19 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agendamento', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='agendamento',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
