# Generated by Django 4.0.3 on 2022-03-18 05:43

from django.db import migrations, models
import users.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('visivel', models.BooleanField(default=True)),
                ('fase', models.IntegerField(blank=True, null=True)),
                ('codigo_si_pni', models.CharField(blank=True, max_length=255, null=True)),
                ('criado_em', models.DateTimeField()),
                ('atualizado_em', models.DateTimeField()),
            ],
            options={
                'verbose_name': 'Grupo de Atendimento',
                'verbose_name_plural': 'Grupos de Atendimento',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('cpf', models.CharField(max_length=11, unique=True, validators=[users.validators.cpf_validator], verbose_name='CPF')),
                ('full_name', models.CharField(blank=True, max_length=255, verbose_name='Nome Completo')),
                ('date_of_birth', models.DateField(null=True, validators=[users.validators.age_validator], verbose_name='Data de Nascimento')),
                ('had_covid_last_month', models.BooleanField(default=False, null=True, verbose_name='Teve Covid nos 30 dias anteriores ao cadastro?')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, related_name='groups', to='users.group')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Usuário',
                'verbose_name_plural': 'Usuários',
            },
        ),
    ]
