# Generated by Django 4.0.3 on 2022-03-18 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='grupo_pai',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
