# Generated by Django 3.1.3 on 2022-03-15 07:26

from django.db import migrations, models
import users.validators


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_full_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='date_of_birth',
            field=models.DateField(null=True, validators=[users.validators.date_of_birth_validator]),
        ),
    ]
