# Generated by Django 3.1.3 on 2022-03-15 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20220315_0426'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='had_covid_last_month',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
